### ISSUE TITLE
Verification game logic discussion

### ISSUE THREAD

**Issue by peara** [leapdao/solEVM-enforcer#107]
I found some cases which do not work under current implementation.
The pieces of code in question is:
https://github.com/leapdao/solEVM-enforcer/blob/master/contracts/Verifier.sol#L146:L154
```
if ((h == dispute.solver.left) || (h == dispute.solver.right)) {
   dispute.state |= SOLVER_RESPONDED;
   dispute.solver = computationPath;
}

if ((h == dispute.challenger.left) || (h == dispute.challenger.right)) {
   dispute.state |= CHALLENGER_RESPONDED;
   dispute.challenger = computationPath;
}
```
and
https://github.com/leapdao/solEVM-enforcer/blob/master/contracts/Verifier.sol#L333:L343
```
if ((dispute.solver.left == dispute.challenger.left) &&
    (dispute.solver.right != 0) &&
    (dispute.challenger.right != 0)) {
    // following right
    dispute.solverPath = dispute.solver.right;
    dispute.challengerPath = dispute.challenger.right;

    if ((dispute.state & START_OF_EXECUTION) != 0) {
        dispute.state ^= START_OF_EXECUTION;
    }
}
```

### Issues
1. The first piece doesn't take in to account the case such as when `h == dispute.solver.left == dispute.challenger.right`. In that case, it will make solver go left and challenger go right. The dispute is completely corrupted at that point. It can be fixed by first checking it is `solver` or `challenger`.

2. The second piece failed in this case:
 **If we solve the case when solver has a bigger tree by adding nodes with `ZERO` hash to challenger tree**
![errorZero](https://user-images.githubusercontent.com/24425403/58104976-e895dd00-7c0f-11e9-8909-c4db89655fd1.png)
The red nodes are visited during dispute.

**Temporary solution**: I tried to solve the above case by replace `ZERO_HASH` with H(H(0,0), H(0,0)). It seem to works, but there might be more cases.

3.
![errorOne](https://user-images.githubusercontent.com/24425403/58105423-b173fb80-7c10-11e9-83fc-c9a5fe100c60.png)
After reaching `Node 2`, solver won't be able to `submitProof` because they don't agree in a common value for `left`. As a result, we don't know who is the correct one.

**Comment by pinkiebell** [comment]
@peara The current logic looks correct to me. Do I oversee something? 🤔

**Comment by peara** [comment]
@pinkiebell 
I think the first case is wrong
The second case is depend on how we handle the case when challenger has a smaller
The third case is depend on https://github.com/leapdao/solEVM-enforcer/blob/master/contracts/Verifier.sol#L189:L191
Nobody can `submitProof` and dispute will be timed out.

**Comment by pinkiebell** [comment]
> The first piece doesn't take in to account the case such as when h == dispute.solver.left == dispute.challenger.right. In that case, it will make solver go left and challenger go right. The dispute is completely corrupted at that point. It can be fixed by first checking it is solver or challenger.

What do you mean with ` it will make solver go left and challenger go right.`. The contract only supports going left or right. And if `right` is `zero` for either solver or challenger, contract will go left

**Comment by peara** [comment]
Ah, I was not clear.
After updateRound run, new solverPath and challengerPath is updated. But the previous values of left and right are not reset.
Since function respond does not separate solver and challenger, there exists a case when the submitted hash eq solver left and challenger right. And that's wrong.
It can be solved by set the value of the unnecessary branch (left in case of following right) to 0.

**Comment by pinkiebell** [comment]
Now it makes sense 😄 .
Indeed a thing that could happen, what do you say to https://github.com/leapdao/solEVM-enforcer/pull/109 ?

I also added the requirement that `compuationPath.left` can never be `zero`.

**Comment by peara** [comment]
I think #109 is OK.
Although I'm still thinking about the way `zero` is handled. I'm trying to drawing some cases now.
