### ISSUE TITLE
create a solver/challenger service based on off-chain interpreter

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/solEVM-enforcer#116]
## Bounty description

have npm package that can be installed globally. it should allow to be started as follows:

- **run as solver:** `solEVM --enforcerADdr="0x1234" --walletPriv="0x3456" --ethProvider`

## Scope
- this will start the process and start listening for new `Request()` and `Register()` events.
- if a `Request()` event is triggered, the process will try to fetch CODE and DATA and try to compute a result.
- if a `Register()` event occurs the process will check if the locally computed result matches the PATH_ROOT registered, if not, it will challenge the result with its local PATH_ROOT.

## Deliverables
- released npm package
- integration tests for full games with contract

## Gain for the project
- visible demo of solEVM

## Roles
bounty gardener: @johannbarbie  / 15%
bounty worker: @sunify  / share
bounty reviewer: @johannbarbie  / 10%

**Comment by pinkiebell** [comment]
@johannbarbie This issue is in progress ;)

**Comment by pinkiebell** [comment]
My bad, will do #122 first 😁
