### ISSUE TITLE
prime casino frontend - events and CD

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/solEVM-enforcer#121]
## Bounty Description

![Prime Casino](https://user-images.githubusercontent.com/659301/58939229-108c5100-8777-11e9-80d9-fad18a4673e8.png)

### Page Requirements

When page loads it first needs to scan all the events from the client contract, to understand which numbers have completed (no bet possible on these), and which numbers are ongoing (bet possible). Results should be kept in local storage, so that next start of the page only scans since the last height. Scanning of events should be done in batches of x00 blocks, so as to not overload the node. While loading events disable all UI and show progress.

## Deliverables
- create page with copy and ui elements for description.
- have page full events from client contract and store in local storage.
- create CD for page under `primality.leapdao.org`

## Gain for the project
- visible demo of solEVM

## Roles
bounty gardener: @johannbarbie / 15%
bounty worker: @sunify  / 65%
bounty reviewer: @MaxStalker  / 20%

**Comment by prastut** [comment]
@johannbarbie interested in contributing :) can you let me know the next steps?
