### ISSUE TITLE
update enforcer interface

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/solEVM-enforcer#122]
## Bounty Description

interface used by client described here: https://docs.google.com/drawings/d/1WXcAvTEpXDGeL68MfWOP20mERht8rzqfSzdiFtYZeSc

## Scope
```
contract IEnforcer {
  event Request(bytes32 indexed executionId, bytes32 codeHash, bytes32 dataHash);
  event Registered(bytes32 indexed executionId, uint256 challengeStartTime, bytes32 pathHash, bytes32 resultHash);

  function request(EVMParameters memory _params, bytes memory _data) public returns (bytes32);
  function getStatus(bytes32 _taskHash) public view returns (uint256, bytes32[] memory, bytes32[] memory)
  function register(bytes32 _executionId, bytes32 _pathHash, bytes32[] _resultProof) public; // first registered pathHash sets challengeStartTime for executionId
  function dispute(bytes32 _executionId, bytes32 _pathHash, bytes32[] _resultProof) public;
  function result(bytes32 _executionId, bytes32 _pathA, bytes32 _pathB, uint256 _result) public; // result: 1 = pathA invalid, 2 = pathB invalid, 3 = both invalid
}
```

## Deliverables
- separate inteface file as above
- fix of enforcer code to match interface
- fix of current tests to pass 

## Gain for the project
- stable client interface

## Roles
bounty gardener: @johannbarbie  / 15%
bounty worker: @pinkiebell  / 75%
bounty reviewer: @johannbarbie  / 10%

**Comment by pinkiebell** [comment]
Kind of blocked by https://github.com/leapdao/solEVM-enforcer/issues/134
Gonna need a redesign first. `struct EVMParameters` ? :)

**Comment by pinkiebell** [comment]
TODO:
enforcer needs a sense of
- `ExecutionRequest`
- `ExecutionResult`
- `ExecutionChallenge`

Also the enforcer should implement a `execution request timeout` so that we have a valid timeframe for a user-supplied time in `request`
