### ISSUE TITLE
add invalidChallengeRate param to solver/challenger service

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/solEVM-enforcer#129]
## Bounty description

extend https://github.com/leapdao/solEVM-enforcer/issues/116 so it can be started as follows:

- **run as solver:** `solEVM --enforcerADdr="0x1234" --walletPriv="0x3456" --ipfsProvider -ethProvider [--onlyChallenger] --invalidChallengeRate=0.x`

## Scope
- if a result can be computed and the `onlyChallenger` is not set, it will submit the solution and exec path root to the enforcer together with a stake.
- if the `invalidChallengeRate` flag is set > 0.0, then in x% of all cases the computation will be halted prematurely at a random opcode.
- for all initialized games in the verifier contract that include it's own PATH_ROOTs  the process will respond on time.

## Deliverables
- integration tests for full games with contract

## Gain for the project
- visible demo of solEVM

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: @sunify  / 65%
bounty reviewer: name / 25%

**Comment by pinkiebell** [comment]
Atm, the ExecutionPoker submits invalid results, a behaviour leftover from unit tests.
I'm gonna remove this and we need to probably resize this bounty to XS. Thoughts?

**Comment by johannbarbie** [comment]
this is not only about the invalid results thought, it is also about all the transactions in verifier: `for all initialized games in the verifier contract that include it's own PATH_ROOTs the process will respond on time`

**Comment by pinkiebell** [comment]
You mean if I restart this service it should check for all open challenges?
Granted. Still needs sizing triage 🙂

**Comment by johannbarbie** [comment]
bounty timed out
