### ISSUE TITLE
Discussion around parameters for stable Enforcer/Verifier interface

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/solEVM-enforcer#134]
As we want to approach a stable interface for the `Enforcer` contract in #122 ,
we have to take care of configurable parameters / arguments makes sense to be configurable by the user.

Thoughts for `request()`:
- `customEnvironmentHash` is missing, important for custom functionality like Plasma Verifier
- parameters for the EVM runtime are missing, which to we want to support?
```
{
  address origin;     // transaction sender
  uint gasPrice;      // gas price of transaction
  uint value;         // wei sent together with the current call

  // MISC
  address coinBase;   // current mining beneficiary
  address caller;     // call sender (excluding delegatecall)
  address target;     // address of the current contract / execution context

  // BLOCK
  bytes32 blockHash;  //
  uint blockNumber;   // 
  uint time;          // timestamp of the current block in seconds since the epoch
  uint difficulty;    // difficulty of the current block
  uint gasLimit;      // block gas limit
}
```
- IPFS hash (of the file) would be different than the hash `sha3(sha256(data), sha256(code))` abi/keccak hashing,
  apart from the fact that we need to take additional data into account. (First two points)

**Comment by johannbarbie** [comment]
for the primeCasino we need none of those, i guess. just set gasLimit to 20M 🤷‍♂

**Comment by pinkiebell** [comment]
@johannbarbie 
what about we specify the interface now, so that we don't have to change it later 😁 
We can talk about those points one-by-one and we can ask around in slack if anyone has an idea of what they would need if they did use solEVM

**Comment by peara** [comment]
The one thing I would absolutely happy to have is a secure random number generator :rofl: 
I think it will be available in Ethereum 2.0, should we support that?
`origin`, `time` and `blockNumber` are also a nice-to-have for many contracts.

**Comment by pinkiebell** [comment]
> The one thing I would absolutely happy to have is a secure random number generator 🤣

💯 

> I think it will be available in Ethereum 2.0, should we support that?

Hmm, the eth 2.0 specs are still in flux, but we need the `customEnvironmentHash` for custom implementations anyway. This could be used for various non-standard thinks in the meantime & future.
Or is this part already finalized? 🙏 😁

**Comment by johannbarbie** [comment]
> time and blockNumber

very important, but need to make sure that it is compatible with solEVM. i suggest to use the value of the root chain at the time when last period submitted. that way even when we do solEVM challenges weeks/month later, the value can be looked up in PlasmaBridge like this: `inclusion proof of tx -> periodRoot -> previous Root -> number + time`. note that the values will be the same for 32 consecutive blocks, not sure if that is a problem.

> origin

signer of tx, same as msg.sender?

**Comment by pinkiebell** [comment]
> origin
> signer of tx, same as msg.sender?

Yes.

**Comment by pinkiebell** [comment]
Draft, what do you think?
```
    /*
     * @dev Structure for the v-game EVM environment.
     */
    struct EVMParameters {
        // Transaction sender
        address origin;
        // address of the current contract / execution context
        address target;
        // blockHash
        bytes32 blockHash;
        // blockNumber
        uint256 blockNumber;
        // timestamp of the current block in seconds since the epoch
        uint256 time;
        // block gas limit - probably not needed
        //   uint256 gasLimit;
        // tx gas limit
        uint256 txGasLimit
        // customEnvironmentHash - for custom implementations like Plasma Exit
        bytes32 customEnvironmentHash;
        // 
        bytes32 codeHash;
        bytes32 dataHash;
    }
```

**Comment by johannbarbie** [comment]
updated the [process flow](https://docs.google.com/drawings/d/1WXcAvTEpXDGeL68MfWOP20mERht8rzqfSzdiFtYZeSc) with `ENV_HASH`, which is a hash of the above struct. ENV_HASH replaces EXEC_ID as identifier for the game.
