### ISSUE TITLE
Include `step` into stateHash

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/solEVM-enforcer#155]
# Bounty

Include `uint256` step into the stateHash. 
This is required to check the position of this execution inside the tree
and more importantly is required for unique leaf hashes.
It's currently possible to have duplicate leave hashes with a correct execution path.
This needs to be fixed.

## Roles
bounty gardener: @pinkiebell  / 10%
bounty worker: name / 70%
bounty reviewer: name / 20%

**Comment by peara** [comment]
Hmm, we already have `pc` in `StateHash`.
So if there exists 2 identical leaves, isn't it mean the execution will loop forever?

**Comment by pinkiebell** [comment]
> Hmm, we already have `pc` in `StateHash`.
> So if there exists 2 identical leaves, isn't it mean the execution will loop forever?

Assume we use the opcode `STOP` we will have zero gas fees for that and because the machine halts after return and the `pc` doesn't get incremented by spec.

I had this one scavenged from my list. Now that you got me thinking, it might be actually not needed. 🤣 
Though having the position in the leaf still helps if we want to verify a proof for a specific leaf at step `N`. 🙂

**Comment by pinkiebell** [comment]
Closing this as we can enforce the same by walking from root to leaves in a specific way.
