### ISSUE TITLE
Present EVM Enforcer at "Blockchain For Science" Conference

### ISSUE THREAD

**Issue by DistributedDoge** [leapdao/solEVM-enforcer#165]
# Bounty

Second edition of[ Blockchain For Science](https://www.blockchainforscience.com/) is happening in Berlin soon. I think presenting EVM Enforcer there could be a gain for the project. If someone is in Berlin the only additional expense to cover is (150EUR) conference ticket and compensation for the work and time involved. 

## Scope
- Submit abstract (till 25th Oct)
- Once abstract is accepted, prepare submission (Best done by 25th but they accept late ones) 
- Prep to make sure one can clearly present EVM Enforcer
- Go to the conference and discuss Enforcer/Leap with scientists and dApp-for-science makers. 

## Deliverables
- Abstract
- Presentation/Poster/Lighting Talk 
- Attending a conference on (4th-5th Nov)

## Gain for the project

- Promoting LeapDAO to Attendees of "Blockchain for Science" (see website)
- Proceedings printed in [Frontiers](https://www.frontiersin.org/) journal (if we want to that is)
- Shows that Leap is capable of presenting research in ways other than self-publishing
- We could use the event to promote in social media, and as track record when applying for grants

## Roles
bounty gardener: @DistributedDoge  / 10%
bounty worker: @DistributedDoge / 75% 
bounty reviewer: @johannbarbie  / 15%

**Comment by johannbarbie** [comment]
paid out here: https://leapdao.slack.com/archives/CAAGW85BR/p1573120487169300
