### ISSUE TITLE
Enable contract mocks for CALL OP-codes in solEVM

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/solEVM-enforcer#23]
When [Leap transaction](https://docs.google.com/document/d/1vStTjqvqZGyiI5AVtpwCIMlHFnzC_4bbixsCfs27-M8) run on Plasma, a virtual state environment is created from the inputs of the transaction:
- For each fungible input an ERC20 mock is created and a balance minted.
- For each non-fungible input an ERC721 mock is created and a token minted.
- A mock for the Plasma bridge is created and the last 100 periods with data are added.

During the execution of a spending condition the CALL and STATICCALL OP-codes are intercepted.
- If the destination of the OP-codes is any other address than the described mocks, the transaction fails. 
- If the destination is one of the mocks, selected functions are executed. 

To create a virtual state environment for Plasma transaction in the EVM enforcer, CALL and STATICCALL OP-codes need to be intercepted in a similar way.
- for `transfer()` on a token contract a LOG event should be emitted.
- for `balanceOf()` on a token contract the input's balance should be returned.
- for `getPeriod()` on the bridge the call should be forwarded to the actual bridge contract.

**Comment by pinkiebell** [comment]
Does these mocks going to exist as separate contracts or builtins of the EthereumRuntime?

**Comment by pinkiebell** [comment]
PlasmaVerifier is the skeleton. Closing this, we can issue a new bounty for more specific functionality
