### ISSUE TITLE
Impossible to track a state(stack, memory, accounts) when JUMP backward

### ISSUE THREAD

**Issue by thomashin** [leapdao/solEVM-enforcer#27]
`JUMP` and `JUMPI` opcode work well but do not seem to work well under one exception. For example, if the current pc is 100(JUMP), JUMP works well with 150(JUMPDEST), but not with 50(JUMPDEST).

I'm testing here.
: https://github.com/Onther-Tech/solEVM/blob/run-erc20/test/ERC20.test.js

_e.g._

2047 has JUMP opcode so we expect to jump to 0x69c(1692).

_pcCount 2047:_
![image](https://user-images.githubusercontent.com/20399507/48993755-fb5cb700-f182-11e8-9090-ed76ffef3d8e.png)

_pcCount 2048:_
![image](https://user-images.githubusercontent.com/20399507/48993848-7e7e0d00-f183-11e8-8d0e-aa70f9031af8.png)

When the pcCount is 2048, it should go to 0x69c(1692), but it does not go.

It's good to jump to a bigger pc(JUMPDEST) than current pc(JUMP), but it doesn't seem to work well when jumping to a smaller pc(JUMPDEST) than current pc(JUMP). Do you happen to know why?

**Comment by thomashin** [comment]
@peara oh I got it. thank you

This is related to this conditional statement(https://github.com/leapdao/solEVM-enforcer/blob/master/contracts/EthereumRuntime.sol#L397).

**Comment by troggy** [comment]
> 2047 has JUMP opcode 

@thomashin which program is that? I'm looking at the flattened ERC20 in your repo and there is no opcode on 2047, only pushdata

**Comment by troggy** [comment]
Anyway, looks like `pcEnd` is not working correct for any programs with JUMPs. Will work on this

**Comment by troggy** [comment]
@thomashin check the fix from #33 please.

On a different note, I noticed that you are [always setting `pcEnd` parameter](https://github.com/Onther-Tech/solEVM/blob/run-erc20/test/ERC20.test.js#L20) which may be inconvenient. If you want to execute the program till the end, you can just set pcEnd/pcCount to 0 or use [`execute` helper](https://github.com/leapdao/solEVM-enforcer/blob/master/test/helpers/runtimeAdapter.js#L34).

**Comment by thomashin** [comment]
I tested [this contract](https://gist.github.com/thomashin/1854445a786a07b93aa15ab610818907). and I deployed `SimpleToken` and called `transfer` function.

Anyway, I want to know VM state after executing JUMP opcode(backward). but I think it seems not working yet.

like the screenshot below, If JUMP opcode executed occupying item(0xe3d, 3645), It should jump to instruction number 3645.
![image](https://user-images.githubusercontent.com/20399507/49565645-34f3a600-f96b-11e8-8af3-60d76330d3ff.png)

I want to know VM state like under the picture.
![image](https://user-images.githubusercontent.com/20399507/49565360-45575100-f96a-11e8-93cf-9339fa5d19cc.png)

after I changed the code like [this](https://github.com/leapdao/solEVM-enforcer/pull/33/files#diff-eeaf807068c53340c80fb1699ba5141bR376), but still not working. we want to know VM state step by step.

**Comment by peara** [comment]
@troggy 
This can be solve with #34 
Instead of `pcEnd`, you will use `pcStepCount` and set it to 1.
Should I update that?

**Comment by johannbarbie** [comment]
resolved by https://github.com/leapdao/solEVM-enforcer/pull/34

**Comment by troggy** [comment]
@thomashin 👋you guys still have Ξ0.5 locked in this bounty on Gitcoin: https://gitcoin.co/issue/leapdao/solEVM-enforcer/27/1866.

Cancel it to get them back :)
