### ISSUE TITLE
Issue #27 not resolved

### ISSUE THREAD

**Issue by thomashin** [leapdao/solEVM-enforcer#38]
#27 is not resolved.

I tested [this contract](https://gist.github.com/thomashin/1854445a786a07b93aa15ab610818907). and I deployed `SimpleToken` and called `transfer` function.

Anyway, I want to know VM state after executing JUMP opcode(backward). but I think it seems not working yet.

like the screenshot below, If JUMP opcode executed occupying item(0xe3d, 3645), It should jump to instruction number 3645.

![image](https://user-images.githubusercontent.com/20399507/49565645-34f3a600-f96b-11e8-8af3-60d76330d3ff.png)

I want to know VM state like under the picture.

![image](https://user-images.githubusercontent.com/20399507/49565360-45575100-f96a-11e8-93cf-9339fa5d19cc.png)

after I changed the code like [this](https://github.com/leapdao/solEVM-enforcer/pull/33/files#diff-eeaf807068c53340c80fb1699ba5141bR376), but still not working. we want to know VM state step by step.

**Comment by thomashin** [comment]
test code should be like this: https://github.com/Onther-Tech/solEVM/commit/5c7605f789534c6482f89dbd91626d524e0a18b1

**Comment by johannbarbie** [comment]
i see, any idea where the error could be?

**Comment by johannbarbie** [comment]
@thomashin can you test again with https://github.com/leapdao/solEVM-enforcer/pull/34 included in master?

**Comment by thomashin** [comment]
@johannbarbie sorry, I'm late. 

I tested the code [here](https://github.com/Onther-Tech/solEVM/tree/test-erc20-token). it works well. 👍 

![image](https://user-images.githubusercontent.com/20399507/50951643-46dbe200-14f1-11e9-8b84-e9322920d947.png)
![image](https://user-images.githubusercontent.com/20399507/50951690-74c12680-14f1-11e9-9b00-500a70f97aa1.png)

![image](https://user-images.githubusercontent.com/20399507/50951654-50fde080-14f1-11e9-9f6a-0d8143fa4c3c.png)
![image](https://user-images.githubusercontent.com/20399507/50951673-67a43780-14f1-11e9-8711-d015e39421e2.png)
