### ISSUE TITLE
EVM - drastically reduce gas consumption

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/solEVM-enforcer#47]
Title says it all.

Ways to do it:
- Code up tooling to assist with optimised assembly (tight jumps?) for branch'ing the opcode handlers
- If that doesn't plays out, maybe we should split each opcode to a sub-contract ?
   In combination with a glue contract...

Thoughts?

**Comment by troggy** [comment]
we can also save some gas by passing structs in public interfaces — we can then throw away a lot of "init" code (if it is still there, haven't looked for a while 😅)

**Comment by pinkiebell** [comment]
I actually made my PR work by using structs.. Seems more like a step & code-size limitation 🤔

**Comment by pinkiebell** [comment]
For reference
#48 #49 #50

**Comment by pinkiebell** [comment]
Closing this one, as I don't want to update this everytime 😎
