### ISSUE TITLE
compact memory proofs with support for ranges | compact calldata proofs

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/solEVM-enforcer#77]
# Bounty

## Scope
- Continue compact mem-proofs with unaligned access support.
- Implement compact calldata proofs
- Both on the JS and SOL side

## Deliverables
👶 
## Gain for the project
⛽️ 
## Roles
bounty gardener: name / share
bounty worker: @pinkiebell / share
bounty reviewer: name / share

**Comment by johannbarbie** [comment]
bounty timed out
