### ISSUE TITLE
Record a video on how to setup local development environment for enforcer

### ISSUE THREAD

**Issue by pinkiebell** [leapdao/solEVM-enforcer#99]
# Bounty

this video extends on the prime casino and shows developers how to run their own computation tasks on the solEVM. 

## Scope
1. start the solver, and register it with the enforcer contract.
2. start the challenger, and register it with the enforcer contract.
3. write a program to solve your computation task in solidity. then deploy it as a contract.
	- you don't need to mind the block gas limit for computation length
	- do not use contract storage in your computation
	- do not use calls to other contracts unless you write a custom call interceptor
4. invoke the solver with the computation parameters (contract + msgData.
   - solver computes result off-chain, and commits solution on-chain
5a. if solution correct, challenge duration expires
5b. if solution incorrect, challenger will start dispute about invalid solution.
	- challenger will also submit valid solution
	- challenge game will be executed, and valid solution will remain as only solution.
7. remaining solution can be used in contract results

## Deliverables
- video showing all steps

## Gain for the project
- deliver next EF milestone

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: @MaxStalker @johannbarbie   / 70% / 20%

**Comment by johannbarbie** [comment]
done
product 1: https://www.youtube.com/watch?v=2eM_27DLfts
product 2: https://youtu.be/D8-zpsZnnDo
